import Navbar from "../components/Navbar";
import styles from "./global.module.css";

export const metadata = {
  title: "Navbar Exercise with React",
  description: "Generated by Next.js",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={styles.body}>
        <Navbar />
        {children}
      </body>
    </html>
  );
}
